# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('abst_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('season', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Fav_Anime',
            fields=[
                ('user_name', models.CharField(max_length=64)),
                ('aid', models.IntegerField()),
                ('watch_degree', models.IntegerField()),
            ],
        ),
    ]
