# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]
    """
    operations = [

        migrations.AddField(
            model_name='user_fav_anime',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
    """
